package estudos;

import java.util.List;
import javax.swing.JComboBox;

public class Enciclopédia extends javax.swing.JFrame {

    /* Variáveis de Sessão */
    private List<Carta> listaCartas = null;
    private CartaDAO cartaDAO = new CartaDAO();
    private Principal telaAnterior;
    private String[] categorias = {"Todas", "Nome", "Fabricante", "Pais", "Potência",
        "Peso", "Velocidade Máxima", "Cilindros", "Cilindradas", "Ano de Fabricação",
        "Super Trunfo", "Not Null"};
    private String[] criterios = {"Igual à", "Diferente de", "Maior e igual à", "Maior que",
        "Menor e igual à", "Menor que", "Parecido com"};

    private void povoarCboxCategoria() {
        for (String aux : categorias) {
            cboxCategoria.addItem(aux);
        }
    }

    private void povoarCboxCriterios() {
        for (String aux : criterios) {
            cboxCriterios.addItem(aux);
        }
    }

    private void povoarTblCartas() {
        tblCartas.setModel(new JTableUtil().geraTabelaCartas(listaCartas));
        if (!listaCartas.isEmpty()) {
            tblCartas.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblCartas.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblCartas.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblCartas.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblCartas.getColumnModel().getColumn(4).setPreferredWidth(90);
            tblCartas.getColumnModel().getColumn(5).setPreferredWidth(65);
            tblCartas.getColumnModel().getColumn(6).setPreferredWidth(65);
            tblCartas.getColumnModel().getColumn(7).setPreferredWidth(75);
            tblCartas.getColumnModel().getColumn(8).setPreferredWidth(120);
        }
        tblCartas.setColumnSelectionAllowed(false);
    }

    /**
     * Creates new form Enciclopédia
     */
    public Enciclopédia() {
        initComponents();
        povoarCboxCategoria();
        povoarCboxCriterios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnciclopedia = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        cboxCategoria = new javax.swing.JComboBox<>();
        cboxCriterios = new javax.swing.JComboBox<>();
        lblTBusca = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblResultados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCartas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Trunfo - Enciclopédia");

        lblEnciclopedia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEnciclopedia.setText("Enciclopédia");

        lblCategoria.setText("Categoria");

        cboxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCategoriaActionPerformed(evt);
            }
        });

        lblTBusca.setText("Tipo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblResultados.setText("Resultados");

        tblCartas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tblCartas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria)
                            .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTBusca)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxCriterios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar))))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnciclopedia)
                            .addComponent(lblResultados)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnciclopedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(lblTBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboxCriterios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addComponent(txtBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCategoriaActionPerformed
        // TODO add your handling code here:
        String s = (String) cboxCategoria.getSelectedItem();
        if (s.equals("Todas") || s.equals("Not Null")) {
            cboxCriterios.setEnabled(false);
            txtBusca.setEnabled(false);
        } else {
            cboxCriterios.setEnabled(true);
            txtBusca.setEnabled(true);
        }

    }//GEN-LAST:event_cboxCategoriaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String s = (String) cboxCategoria.getSelectedItem();
        String s2 = "";
        /*{"Potência", "Peso", "Velocidade Máxima", "Cilindros", "Cilindradas", "Ano de Fabricação",
        "Super Trunfo", "Not Null"};*/
        switch (s) {
            case "Todas":
                listaCartas = cartaDAO.listar();
                povoarTblCartas();
                break;
            case "Nome":
                s2 = (String) cboxCriterios.getSelectedItem();
                switch (s2) {
                    case "Igual à":
                        listaCartas = cartaDAO.listarEquals("nome", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Diferente de":
                        listaCartas = cartaDAO.listarNotEquals("nome", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Maior e igual à":
                        listaCartas = cartaDAO.listarGreaterEquals("nome", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Maior que":
                        listaCartas = cartaDAO.listarGreaterThen("nome", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Menor e igual à":
                        listaCartas = cartaDAO.listarLessEquals("nome", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Menor que":
                        listaCartas = cartaDAO.listarLessThen("nome", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Parecido com":
                        listaCartas = cartaDAO.listarIlike("nome", txtBusca.getText().toUpperCase().toString());
                        break;
                }
                povoarTblCartas();
                break;
            case "Fabricante":
                s2 = (String) cboxCriterios.getSelectedItem();
                switch (s2) {
                    case "Igual à":
                        listaCartas = cartaDAO.listarEquals("fabricante", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Diferente de":
                        listaCartas = cartaDAO.listarNotEquals("fabricante", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Maior e igual à":
                        listaCartas = cartaDAO.listarGreaterEquals("fabricante", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Maior que":
                        listaCartas = cartaDAO.listarGreaterThen("fabricante", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Menor e igual à":
                        listaCartas = cartaDAO.listarLessEquals("fabricante", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Menor que":
                        listaCartas = cartaDAO.listarLessThen("fabricante", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Parecido com":
                        listaCartas = cartaDAO.listarIlike("fabricante", txtBusca.getText().toUpperCase().toString());
                        break;
                }
                povoarTblCartas();
                break;
            case "Pais":
                s2 = (String) cboxCriterios.getSelectedItem();
                switch (s2) {
                    case "Igual à":
                        listaCartas = cartaDAO.listarEquals("pais", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Diferente de":
                        listaCartas = cartaDAO.listarNotEquals("pais", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Maior e igual à":
                        listaCartas = cartaDAO.listarGreaterEquals("pais", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Maior que":
                        listaCartas = cartaDAO.listarGreaterThen("pais", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Menor e igual à":
                        listaCartas = cartaDAO.listarLessEquals("pais", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Menor que":
                        listaCartas = cartaDAO.listarLessThen("pais", txtBusca.getText().toUpperCase().toString());
                        break;
                    case "Parecido com":
                        listaCartas = cartaDAO.listarIlike("pais", txtBusca.getText().toUpperCase().toString());
                        break;
                }
                povoarTblCartas();
                break;
            case "Potência":
                s2 = (String) cboxCriterios.getSelectedItem();
                switch (s2) {
                    case "Igual à":
                        listaCartas = cartaDAO.listarEquals("potencia", new Float(txtBusca.getText().toUpperCase().toString()));
                        break;
                    case "Diferente de":
                        listaCartas = cartaDAO.listarNotEquals("potencia", new Float(txtBusca.getText().toUpperCase().toString()));
                        break;
                    case "Maior e igual à":
                        listaCartas = cartaDAO.listarGreaterEquals("potencia", new Float(txtBusca.getText().toUpperCase().toString()));
                        break;
                    case "Maior que":
                        listaCartas = cartaDAO.listarGreaterThen("potencia", new Float(txtBusca.getText().toUpperCase().toString()));
                        break;
                    case "Menor e igual à":
                        listaCartas = cartaDAO.listarLessEquals("potencia", new Float(txtBusca.getText().toUpperCase().toString()));
                        break;
                    case "Menor que":
                        listaCartas = cartaDAO.listarLessThen("potencia", new Float(txtBusca.getText().toUpperCase().toString()));
                        break;
                    case "Parecido com":
                        listaCartas = cartaDAO.listarIlike("potencia", txtBusca.getText().toUpperCase().toString());
                        break;
                }
                povoarTblCartas();
                break;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enciclopédia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enciclopédia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cboxCategoria;
    private javax.swing.JComboBox<String> cboxCriterios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblEnciclopedia;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblTBusca;
    private javax.swing.JTable tblCartas;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
