/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  bruno
 * Created: 25/06/2016
 */

DROP TABLE CARTA;
DROP TABLE CARRO;

CREATE TABLE CARRO (ID SERIAL PRIMARY KEY, 
                    NOME VARCHAR(30) NOT NULL,
                    FABRICANTE VARCHAR(30) NOT NULL,
                    PAIS VARCHAR(30) NOT NULL,
                    POTENCIA DECIMAL NOT NULL,
                    PESO DECIMAL NOT NULL,
                    VMAX DECIMAL NOT NULL,
                    CILINDROS INTEGER NOT NULL,
                    CC INTEGER NOT NULL,
                    ANO INTEGER NOT NULL,
                    IMAGEM VARCHAR(150) NOT NULL);

CREATE TABLE CARTA (ID SERIAL PRIMARY KEY, 
                    NUMERO INTEGER NOT NULL, 
                    LETRA VARCHAR(1) NOT NULL, 
                    SUPERTRUNFO BOOLEAN NOT NULL, 
                    SELECIONADA BOOLEAN NOT NULL,
                    DESCARTADA BOOLEAN not null,
                    CARRO INTEGER NOT NULL,
                    NUM_VITORIAS INTEGER NOT NULL,
                    NUM_EMPATES INTEGER NOT NULL,
                    NUM_DERROTAS INTEGER NOT NULL,
                    CONSTRAINT FK_CARRO FOREIGN KEY(CARRO) REFERENCES CARRO(ID));

INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('919 HYBRID', 'PORSCHE', 'ALEMANHA', 900.0, 875.0, 340.2, 4, 2000, 2015, 'Porsche919.png');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('F1', 'MCLAREN', 'INGLATERRA', 618.0, 1138.0, 390.7, 12, 6100, 1992, 'McLarenF1.png');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('VULCAN', 'ASTON MARTIN', 'INGLATERRA', 800.0, 1350.0, 360.0, 12, 7000, 2015, 'IMG1.PNG');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('CHIRON', 'BUGATTI', 'FRANÇA', 1479.0, 1995.8, 420.0, 16, 8000, 2016, 'IMG1.PNG');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('ONE:1', 'KOENIGSEGG', 'SUÉCIA', 1360.0, 1360.0, 453.0, 8, 5000, 2014, 'IMG1.PNG');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('LA FERRARI', 'FERRARI', 'ITÁLIA', 800.0, 1585.0, 349.0, 12, 3800, 2013, 'IMG1.PNG');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('GT-R R35', 'NISSAN', 'JAPÂO', 485.0, 1736.0, 315.0, 6, 6300, 2008, 'IMG1.PNG');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('ZONDA CINQUE', 'PAGANI', 'ITÁLIA', 678.0, 1210.0, 350.0, 12, 7200, 2008, 'IMG1.PNG');
INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('CAMARO SS', 'CHEVROLET', 'EUA', 406.0, 1570.0, 249.0, 8, 6200, 2009, 'IMG1.PNG');

INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (1, 'A', FALSE, FALSE, FALSE, 1, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (1, 'B', FALSE, FALSE, FALSE, 2, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (1, 'C', FALSE, FALSE, FALSE, 3, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (1, 'D', FALSE, FALSE, FALSE, 4, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (1, 'E', FALSE, FALSE, FALSE, 5, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (2, 'A', FALSE, FALSE, FALSE, 6, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (2, 'B', FALSE, FALSE, FALSE, 7, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (2, 'C', FALSE, FALSE, FALSE, 8, 0,0,0);
INSERT INTO CARTA (NUMERO, LETRA, SUPERTRUNFO, SELECIONADA, DESCARTADA, CARRO, NUM_VITORIAS, NUM_EMPATES, NUM_DERROTAS) VALUES  (2, 'D', FALSE, FALSE, FALSE, 9, 0,0,0);

INSERT INTO CARRO (NOME, FABRICANTE, PAIS, POTENCIA, PESO, VMAX, CILINDROS, CC, ANO, IMAGEM) VALUES ('MARAUDER', 'PARAMOUNT GROUP', 'AFRICA DO SUL', 1138.0, 9900.0, 120.0, 4, 5900, 2008, '/resources/imagens/IMG1.PNG');









